---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups: [""]
  resources: 
  - configmaps
  - namespaces
  verbs: 
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  verbs: 
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.devicechain.io
  resources:
  - instances
  - instanceconfigurations
  - microservices
  - microserviceconfigurations
  - tenants  
  - tenantmicroservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.devicechain.io
  resources:
  - instances/finalizers
  - microservices/finalizers
  - tenants/finalizers
  - tenantmicroservices/finalizers
  verbs:
  - update
- apiGroups:
  - core.devicechain.io
  resources:
  - instances/status
  - microservices/status
  - tenants/status
  - tenantmicroservices/status
  verbs:
  - get
  - patch
  - update
