# permissions for end users to view microserviceconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: microserviceconfiguration-viewer-role
rules:
- apiGroups:
  - core.devicechain.io
  resources:
  - microserviceconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.devicechain.io
  resources:
  - microserviceconfigurations/status
  verbs:
  - get
