---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - core.devicechain.io
  resources:
  - instances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.devicechain.io
  resources:
  - instances/finalizers
  verbs:
  - update
- apiGroups:
  - core.devicechain.io
  resources:
  - instances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.devicechain.io
  resources:
  - microservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.devicechain.io
  resources:
  - microservices/finalizers
  verbs:
  - update
- apiGroups:
  - core.devicechain.io
  resources:
  - microservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.devicechain.io
  resources:
  - tenantmicroservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.devicechain.io
  resources:
  - tenantmicroservices/finalizers
  verbs:
  - update
- apiGroups:
  - core.devicechain.io
  resources:
  - tenantmicroservices/status
  verbs:
  - get
  - patch
  - update
