# permissions for end users to view tenants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenant-viewer-role
rules:
- apiGroups:
  - core.devicechain.io
  resources:
  - tenants
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.devicechain.io
  resources:
  - tenants/status
  verbs:
  - get
